owner: LonelyJupiter # GitHub username
repo: UPPTIME # GitHub repository name
sites: # List of endpoints to track
  - name: la
    url:  $LA
  - name: jp
    url: $JP
  - name: jpvir
    url: $JPVIR
  - name: sg
    url: $SG
  - name: hk1
    url: $HK1
  - name: hk2
    url: $HK2
  - name: cac
    url: $CAC
  - name: kr
    url: $KR
  - name: eu1
    url: $EU1
  - name: eu2
    url: $EU2
  - name: eu3
    url: $EU3
    
assignees: # Users to assign downtime issues (optional)
  - LonelyJupiter
status-website: # Status website (optional)
  cname: www.skrr.eu.org # Custom domain CNAME
  name: UPPTIME # Status website title
status-website:
  theme: dark