owner: LonelyJupiter # GitHub username
repo: UPPTIME # GitHub repository name
sites: # List of endpoints to track
  - name: la
    url: https://la.sf-auto.cf
  - name: jp
    url: https://jp.sf-auto.tk
  - name: jpvir
    url: https://jpvir.sf-auto.tk
  - name: sg
    url: https://v4.trap.eu.org
  - name: hk1
    url: https://hkv4.wink.ga
  - name: hk2
    url: https://hk2v4.wink.ga
  - name: cac
    url: https://niubi.tk
  - name: kr
    url: https://oracle.sf-auto.tk
  - name: eu1
    url: https://euserv1.niubi.tk
  - name: eu2
    url: https://euserv2.niubi.tk
  - name: eu3
    url: https://euserv3.niubi.tk
    
assignees: # Users to assign downtime issues (optional)
  - LonelyJupiter
status-website: # Status website (optional)
  cname: www.skrr.eu.org # Custom domain CNAME
  name: UPPTIME # Status website title