owner: LonelyJupiter # GitHub username
repo: UPPTIME # GitHub repository name
sites: # List of endpoints to track
  - name: hk1
    url: $HK1
  - name: hk2
    url: $HK2
  - name: cac
    url: $CAC
    expectedStatusCodes:
      - 403
  - name: jp
    url: $JP
  - name: sg
    url: $SG
  - name: eu1
    url: $EU1
  - name: eu2
    url: $EU2
    expectedStatusCodes:
      - 403
  - name: eu3
    url: $EU3
    expectedStatusCodes:
      - 403
  - name: kr
    url: $KR
  - name: jpvir
    url: $JPVIR
    maxResponseTime: 10000
  - name: la
    url: $LA
    
assignees: # Users to assign downtime issues (optional)
  - LonelyJupiter
status-website: # Status website (optional)
  cname: www.skrr.eu.org # Custom domain CNAME
  name: 全球服务器状态网 # Status website title
  theme: dark
  logoUrl: https://preston.cf/preston.gif
  favicon: https://preston.cf/preston.gif

